version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: directus_database
    volumes:
      - directus_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: directus_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  directus:
    image: directus/directus:latest
    container_name: directus_app
    ports:
      - "8055:8055"
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      # General Configuration
      KEY: 'your-random-secret-key-here'
      SECRET: 'your-random-secret-here'
      
      # Database Configuration
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      
      # Cache Configuration
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      
      # Admin User (Initial Setup)
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'ChangeMeImmediately!'
      
      # Optional: Email Configuration
      # EMAIL_FROM: 'no-reply@example.com'
      # EMAIL_TRANSPORT: 'smtp'
      # EMAIL_SMTP_HOST: 'smtp.example.com'
      # EMAIL_SMTP_PORT: '587'
      # EMAIL_SMTP_USER: 'username'
      # EMAIL_SMTP_PASSWORD: 'password'
      # EMAIL_SMTP_SECURE: 'false'
      
      # Optional: File Storage (S3 Example)
      # STORAGE_LOCATIONS: 's3'
      # STORAGE_S3_DRIVER: 's3'
      # STORAGE_S3_KEY: 'your-s3-key'
      # STORAGE_S3_SECRET: 'your-s3-secret'
      # STORAGE_S3_BUCKET: 'your-bucket-name'
      # STORAGE_S3_REGION: 'us-east-1'
      
      # Optional: Public URL
      # PUBLIC_URL: 'https://your-domain.com'
      
      # Optional: CORS
      # CORS_ENABLED: 'true'
      # CORS_ORIGIN: 'true'
      
      # Optional: Rate Limiting
      # RATE_LIMITER_ENABLED: 'true'
      # RATE_LIMITER_STORE: 'redis'
      # RATE_LIMITER_REDIS: 'redis://cache:6379'
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8055/server/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  directus_data:
    driver: local
  directus_uploads:
    driver: local
  directus_extensions:
    driver: local

networks:
  default:
    name: directus_network
